services:
  api-server:
    image: ahmedhesham301/hetzner-api-server
    build:
      context: .
      dockerfile: api-server/Dockerfile
    container_name: api-server
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - GRAFANA_HOST=grafana:3000
      - CONTROLLER_HOST=control-plane
      - CONTROLLER_PORT=8085
    env_file:
      - .env.compose
    depends_on:
      db:
        condition: service_healthy

  control-plane:
    image: ahmedhesham301/hetzner-control-plane
    build:
      context: .
      dockerfile: control-plane/Dockerfile
    container_name: control-plane
    restart: unless-stopped
    ports:
      - 8085:8085
    environment:
      - DATABASE_HOST=db
    env_file:
      - .env.compose
    depends_on:
      db:
        condition: service_healthy

  db-control-plane:
    image: ahmedhesham301/hetzner-db-control-plane:latest
    build:
      context: .
      dockerfile: db-control-plane/Dockerfile
    container_name: db-control-plane
    restart: unless-stopped
    ports:
      - 8090:8090
    environment:
      - BUILD_TARGET=hetzner
      - TEMPORAL_ADDRESS=temporal:7233
      - DATABASE_HOST=db
      - PACKER_TEMPLATES_PATH=/packer-templates
    env_file:
      - .env.compose
    volumes:
      - ./packer-templates:/packer-templates:ro
    depends_on:
      temporal:
        condition: service_healthy
      db:
        condition: service_healthy
      alloy:
        condition: service_started

  db:
    image: postgres:18-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./configs/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver

  alloy:
    image: grafana/alloy:v1.19.2
    container_name: alloy
    restart: unless-stopped
    volumes:
      - ./configs/alloy:/etc/alloy/
    ports:
      - 12345:12345
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy
    environment:
      - DATABASE_OS_TARGETS=http://172.17.0.1:8090/services/os/targets
      - DB_CONTROL_PLANE_HOST=172.17.0.1
      - DB_CONTROL_PLANE_PORT=8090

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro

  vault:
    image: hashicorp/vault:2.0
    container_name: vault
    restart: unless-stopped
    ports:
      - 8200:8200

  temporal-postgresql:
    image: postgres:18-alpine
    container_name: temporal-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s

  temporal-admin-tools:
    image: temporalio/admin-tools:1.31
    container_name: temporal-admin-tools
    restart: on-failure:6
    depends_on:
      temporal-postgresql:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - SQL_PASSWORD=temporal
    volumes:
      - ./scripts/temporal:/scripts
    entrypoint: ["/bin/sh"]
    command: /scripts/setup-postgres.sh

  temporal:
    image: temporalio/server:1.31
    container_name: temporal
    restart: unless-stopped
    depends_on:
      temporal-admin-tools:
        condition: service_completed_successfully
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - BIND_ON_IP=0.0.0.0
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/dynamic-config.yaml
    ports:
      - 7233:7233
    volumes:
      - ./configs/temporal/dynamic-config.yaml:/etc/temporal/config/dynamicconfig/dynamic-config.yaml
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7233"]
      interval: 5s
      timeout: 3s
      start_period: 30s
      retries: 60

  temporal-create-namespace:
    image: temporalio/admin-tools:1.31
    container_name: temporal-create-namespace
    restart: on-failure:5
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DEFAULT_NAMESPACE=default
    volumes:
      - ./scripts/temporal:/scripts
    entrypoint: ["/bin/sh"]
    command: /scripts/create-namespace.sh

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
      - TEMPORAL_CSRF_COOKIE_INSECURE=true
    image: temporalio/ui:2.53.3
    restart: unless-stopped
    ports:
      - 2000:8080
